version: '3.8'
services:
  # Database service
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: braian
      POSTGRES_PASSWORD: braianpass
      POSTGRES_DB: braian_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U braian -d braian_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:8080'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://braian:braianpass@db:5432/braian_dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080/api/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
